version: '3.8'

services:
  app:
    container_name: project_manager
    build: .
    env_file:
      - .env
    ports:
      - "8080:8080"
    volumes:
      - .:/usr/src/app
    depends_on:
      - postgres
    networks:
      - fullstack

  postgres:
    image: postgres:latest
    container_name: db_postgres1
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - database_postgres:/var/lib/postgresql/data
    networks:
      - fullstack

volumes:
  database_postgres:

networks:
  fullstack:
    driver: bridge